"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { getDailyPlan, type PlannedMeal, type DailyPlan } from "@/lib/api";
import { useUserId } from "@/lib/auth";

const MEAL_ORDER: Record<PlannedMeal["meal_type"], number> = {
  breakfast: 0, lunch: 1, dinner: 2, snack: 3,
};

const MEAL_ICON: Record<PlannedMeal["meal_type"], string> = {
  breakfast: "wb_sunny",
  lunch:     "lunch_dining",
  dinner:    "dinner_dining",
  snack:     "bakery_dining",
};

export default function Plan() {
  const userId = useUserId();
  const [plan, setPlan] = useState<DailyPlan | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const fetchPlan = useCallback(() => {
    setLoading(true);
    setError("");
    getDailyPlan(userId)
      .then(setPlan)
      .catch((e: Error) => setError(e.message))
      .finally(() => setLoading(false));
  }, [userId]);

  useEffect(() => { fetchPlan(); }, [fetchPlan]);

  const meals = plan?.meals
    ? [...plan.meals].sort((a, b) => MEAL_ORDER[a.meal_type] - MEAL_ORDER[b.meal_type])
    : [];

  return (
    <>
      {/* Header */}
      <section className="space-y-3">
        <span className="text-primary font-bold text-xs tracking-widest uppercase block">
          AI Curated
        </span>
        <h1 className="font-headline text-4xl md:text-5xl font-extrabold tracking-tighter text-on-surface leading-[1.05]">
          Today&rsquo;s <span className="italic text-primary">plan.</span>
        </h1>
        <p className="text-on-surface-variant max-w-md leading-relaxed">
          A few ideas for the rest of your day, built around what&rsquo;s already in
          your pantry and what you&rsquo;ve eaten so far.
        </p>
      </section>

      {/* AI summary card */}
      {plan && !loading && (
        <section className="relative overflow-hidden rounded-xl p-8 bg-surface-container-lowest shadow-sm">
          <div className="absolute top-0 right-0 p-4 opacity-10 pointer-events-none">
            <span className="material-symbols-outlined" style={{ fontSize: "6rem" }}>
              auto_awesome
            </span>
          </div>
          <div className="relative z-10">
            <p className="font-headline text-on-surface-variant text-xs font-bold tracking-widest uppercase mb-3">
              Why this plan
            </p>
            <p className="font-headline text-xl md:text-2xl font-extrabold tracking-tight text-on-surface leading-snug">
              {plan.summary}
            </p>
            {plan.model_used && (
              <p className="mt-4 text-[10px] uppercase tracking-widest text-on-surface-variant font-bold">
                Generated by {plan.model_used}
              </p>
            )}
          </div>
        </section>
      )}

      {/* Auto-saved to calendar banner */}
      {plan && !loading && meals.length > 0 && (
        <Link
          href="/calendar"
          className="flex items-center gap-2.5 rounded-lg bg-primary-container/30 border border-primary/15 px-4 py-2.5 transition-colors hover:bg-primary-container/50"
        >
          <span className="material-symbols-outlined material-symbols-filled text-primary text-lg">
            event_available
          </span>
          <span className="text-sm font-semibold text-on-primary-container">
            Meals added to your calendar
          </span>
          <span className="material-symbols-outlined text-on-primary-container/60 text-base ml-auto">
            arrow_forward
          </span>
        </Link>
      )}

      {/* Refresh button */}
      <section className="flex items-center justify-between gap-3">
        <h2 className="font-headline text-xl font-bold tracking-tight text-on-surface">
          Meal suggestions
        </h2>
        <button
          onClick={fetchPlan}
          disabled={loading}
          className="btn-primary text-sm flex items-center gap-2"
        >
          <span className={`material-symbols-outlined text-base ${loading ? "animate-spin" : ""}`}>
            {loading ? "progress_activity" : "refresh"}
          </span>
          {loading ? "Generating…" : "Generate new plan"}
        </button>
      </section>

      {/* Error */}
      {error && !loading && (
        <div className="bg-error-container/20 border-l-4 border-error rounded-xl p-5 space-y-3">
          <p className="text-sm text-on-error-container font-semibold">
            Couldn&rsquo;t generate a plan. Make sure you have items in your pantry and try again.
          </p>
          <p className="text-xs text-on-surface-variant">{error}</p>
          <button onClick={fetchPlan} className="btn-soft text-sm">
            Retry
          </button>
        </div>
      )}

      {/* Loading skeleton */}
      {loading && !plan && (
        <section className="card-soft flex flex-col items-center justify-center py-16 space-y-4">
          <span className="material-symbols-outlined material-symbols-filled text-primary text-5xl animate-pulse">
            eco
          </span>
          <p className="font-headline text-lg font-bold text-on-surface">
            Cooking up your plan&hellip;
          </p>
          <p className="text-xs text-on-surface-variant max-w-xs text-center">
            Reading your pantry, scanning today&rsquo;s log, and asking the AI for ideas.
            This can take a few seconds.
          </p>
        </section>
      )}

      {/* Meal cards */}
      {!loading && meals.length > 0 && (
        <section className="space-y-4">
          {meals.map((meal, idx) => (
            <article key={`${meal.meal_type}-${idx}`} className="card-soft space-y-4">
              {/* Meal-type pill + calendar badge */}
              <div className="flex items-center justify-between gap-3">
                <span className="inline-flex items-center gap-2 bg-surface-container-low text-on-surface-variant px-3 py-1 rounded-full text-[10px] font-bold font-label uppercase tracking-widest">
                  <span className="material-symbols-outlined text-sm">
                    {MEAL_ICON[meal.meal_type]}
                  </span>
                  {meal.meal_type}
                </span>
                <div className="flex items-center gap-2">
                  <span className="inline-flex items-center gap-1 text-primary/70 text-[10px] font-bold uppercase tracking-widest">
                    <span className="material-symbols-outlined material-symbols-filled text-sm">
                      event_available
                    </span>
                    Saved
                  </span>
                  <span className="text-[10px] uppercase tracking-widest font-bold text-on-surface-variant">
                    #{idx + 1}
                  </span>
                </div>
              </div>

              {/* Name */}
              <h3 className="font-headline text-2xl font-bold tracking-tight text-on-surface leading-tight">
                {meal.name}
              </h3>

              {/* Macros */}
              <div className="flex flex-wrap gap-2">
                {[
                  { l: "kcal",    v: meal.calories },
                  { l: "protein", v: meal.protein_g, u: "g" },
                  { l: "carbs",   v: meal.carbs_g,   u: "g" },
                  { l: "fat",     v: meal.fat_g,     u: "g" },
                ].map(({ l, v, u }) => (
                  <span key={l} className="bg-surface-container-low rounded-lg px-2.5 py-1 text-[11px]">
                    <span className="font-bold">{Math.round(v)}{u ?? ""}</span>
                    <span className="text-on-surface-variant ml-1">{l}</span>
                  </span>
                ))}
              </div>

              {/* Ingredients */}
              {meal.ingredients.length > 0 && (
                <div>
                  <p className="text-[10px] uppercase tracking-widest font-bold text-on-surface-variant mb-2">
                    Ingredients
                  </p>
                  <div className="flex flex-wrap gap-2">
                    {meal.ingredients.map((ing) => {
                      const usesInv = meal.uses_inventory.some(
                        (i) => i.toLowerCase() === ing.toLowerCase()
                      );
                      return usesInv ? (
                        <span
                          key={ing}
                          className="inline-flex items-center gap-1.5 bg-primary-container/40 text-on-primary-container px-3 py-1.5 rounded-full text-xs font-semibold border border-primary/20"
                        >
                          <span className="material-symbols-outlined text-sm material-symbols-filled">
                            kitchen
                          </span>
                          {ing}
                        </span>
                      ) : (
                        <span
                          key={ing}
                          className="inline-flex items-center gap-1.5 bg-surface-container-high px-3 py-1.5 rounded-full text-xs font-medium border border-outline-variant/10"
                        >
                          <span className="w-1.5 h-1.5 rounded-full bg-on-surface-variant/40" />
                          {ing}
                        </span>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Reason */}
              {meal.reason && (
                <p className="text-sm text-on-surface-variant leading-relaxed border-t border-outline-variant/20 pt-3">
                  {meal.reason}
                </p>
              )}
            </article>
          ))}
        </section>
      )}

      {/* Empty state when no error, not loading, and no meals */}
      {!loading && !error && plan && meals.length === 0 && (
        <section className="card-soft text-center py-12 space-y-3">
          <span className="material-symbols-outlined text-on-surface-variant text-4xl">
            restaurant_menu
          </span>
          <p className="font-headline text-lg font-bold text-on-surface">
            No suggestions right now.
          </p>
          <p className="text-sm text-on-surface-variant">
            Add a few items to your pantry, then generate a new plan.
          </p>
        </section>
      )}

      {/* Disclaimer */}
      <p className="text-on-surface-variant text-xs text-center pt-2">
        Suggestions only &mdash; not medical or dietary advice.
      </p>
    </>
  );
}
